'use strict';

/**
 * @file engine.js
 * @description Core Security Orchestrator for ShieldWall WAF.
 * Acts as the primary decision engine unifying signatures, behavioral heuristics, and rate limiting.
 *
 * ROLE IN ARCHITECTURE:
 * Central brain that sequences the request through 12 analysis layers (Go TLS -> Decoder -> Modules -> Rules).
 * It aggregates risk scores from independent modules and applies cross-module signal boosting.
 *
 * @dependencies
 * - `decoder.js`: Input normalization payload unpacking.
 * - `rule-parser.js` & `rule-matcher.js`: YARA-inspired signature evaluation.
 * - `reputation.js`: Time-decaying threat intelligence store (used for FP Circuit Breakers).
 * - `recon-tracker.js`: Reconnaissance-to-Exploit correlation engine (Kill Chain detection).
 *
 * @flow
 * 1. Intakes raw HTTP requests (`req`).
 * 2. `_extractIP`: Computes real IP handling proxy topologies.
 * 3. `decodeRequest`: Unrolls encodings (URL, base64, HTML entities).
 * 4. Extracts Signals: Runs Detectors concurrently (Modules + .shield rules).
 * 5. Risk Aggregation: Combines signals weighted by Action Sensitivity (Context).
 * 6. Recon Correlation: Checks IP taint from reconnaissance tracker.
 * 7. Circuit Breaker: Evaluates history to prevent False Positives for established users.
 * 8. Policy Enforcement: Blocks or logs.
 *
 * CRITICAL FALSE POSITIVE (FP) MITIGATION:
 * - Action Sensitivity Context: Multiplies risk only for critical endpoints (auth/admin).
 * - Reputation Circuit Breaker: Discounts risk for established, trust-verified users.
 * - Feedback Loop: Integrates backend latency and response codes to refine verdicts.
 */

const { EventEmitter } = require('events');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const { decodeRequest } = require('./decoder');
const { parseRules, loadRulesFromDir } = require('./rule-parser');
const { matchAllRules } = require('./rule-matcher');
const Logger = require('./logger');
const ReportingEngine = require('./reporting');
const MitigationEngine = require('./mitigation');
const Advisor = require('./advisor');
const { recordReconAttempt, getReputationTaint, isSensitiveTarget } = require('./recon-tracker');

const DEFAULT_RULES_DIR = path.join(__dirname, '..', '..', 'rules');
const SEVERITY_PRIORITY = { critical: 4, high: 3, medium: 2, low: 1, info: 0 };
const SEVERITY_WEIGHTS = { critical: 100, high: 50, medium: 20, low: 10, info: 1 };
const MAX_AUTO_RULES = 50;
const AUTO_RULE_TTL_DAYS = 7;

/**
 * Action Sensitivity Context Matrix
 * Multiplies anomaly scores based on the operational severity of the endpoint.
 * Protects against False Positives generated by noisy interaction on low-risk public pages.
 */
const ENDPOINT_SENSITIVITY = [
  { pattern: /^\/(auth|login|register|reset-password|oauth|sso)/i, multiplier: 2.5 },
  { pattern: /^\/(admin|cms|wp-admin|dashboard|control-panel)/i, multiplier: 3.0 },
  { pattern: /^\/api\/v[0-9]+\/(payment|checkout|cart|billing)/i, multiplier: 2.0 },
  { pattern: /^\/(search|catalog|public|assets|_next|static)/i, multiplier: 0.2 },
  { pattern: /.*/, multiplier: 1.0 }
];

class ShieldWallEngine extends EventEmitter {
  /**
   * Initializes the WAF Engine.
   * @param {Object} options - Configuration options.
   * @param {string} options.mode - 'block' | 'log'.
   * @param {boolean} options.trustProxy - Required to securely parse X-Forwarded-For.
   */
  constructor(options = {}) {
    super();

    this.options = {
      mode: options.mode || 'block',
      logLevel: options.logLevel || 'info',
      jsonLogs: options.jsonLogs || false,
      silent: options.silent || false,
      rulesDir: options.rulesDir || DEFAULT_RULES_DIR,
      customRules: options.customRules || null,
      customRulesFiles: options.customRulesFiles || [],
      blockStatusCode: options.blockStatusCode || 403,
      blockMessage: options.blockMessage || null,
      trustProxy: options.trustProxy || false,
      excludePaths: options.excludePaths || [],
      excludeIPs: options.excludeIPs || [],
      blockThreshold: options.blockThreshold || 100,
      modules: {
        anomaly: true, smartAnomaly: true, honeypot: true,
        pathTraversal: true, commandInjection: true,
        botDetection: true, sessionAnomaly: true, apiAbuse: true,
        ddosProtection: true, fingerprinter: true, reputation: true,
        ...(options.modules || {}),
      },
      autoGenerateRules: options.autoGenerateRules !== false,
    };

    this._autoGeneratedHashes = new Set();
    this.logger = new Logger({
      level: this.options.logLevel,
      silent: this.options.silent,
      json: this.options.jsonLogs,
      siemWebhook: options.siemWebhook || null,
      maxHistory: options.maxHistory || 10000,
      onEvent: (event) => this.emit('log', event),
    });

    this.mitigation = new MitigationEngine(options.mitigation || {});

    this.rules = [];
    this._loadRules();

    this.modules = [];
    this._loadModules();

    this.stats = { totalRequests: 0, blockedRequests: 0, detectedThreats: 0, startTime: Date.now() };

    this.reporting = null;
    if (options.reporting !== false) {
      this.reporting = new ReportingEngine({
        enabled: true,
        reportsDir: options.reportsDir,
        maxStoredReports: options.maxStoredReports,
        logger: this.logger,
        onReport: (report) => this.emit('report', report),
      });
    }

    this.logger.info('Engine initialized', {
      mode: this.options.mode,
      rulesLoaded: this.rules.length,
      modulesActive: this.modules.map(m => m.name),
    });

    this._setupClusterSync();
  }

  /**
   * Synchronizes internal state across Node.js worker processes via IPC.
   */
  _setupClusterSync() {
    if (typeof process.send !== 'function') return;

    process.on('message', (msg) => {
      if (msg?.type === 'SHIELDWALL_SYNC_ATTACK') {
        // Sync attack from another worker into local logger (without triggering re-emit)
        this.logger._store(msg.data);
      }
    });

    this.on('threat', (event) => {
      process.send({
        type: 'SHIELDWALL_SYNC_ATTACK',
        data: event
      });
    });
  }

  /**
   * Resolves the true client IP safely, accounting for reverse proxies.
   * Prevents Proxy Blindness bugs where 'req.ip' maps to Cloudflare or a Load Balancer.
   * @param {Object} req - Inbound HTTP request.
   * @returns {string} The canonical client IP address.
   */
  _extractIP(req) {
    if (this.options.trustProxy && req.headers && req.headers['x-forwarded-for']) {
      // Parse multi-tier proxies, grabbing the original public client
      const ips = req.headers['x-forwarded-for'].split(',').map(ip => ip.trim());
      if (ips.length > 0) return ips[0];
    }
    return req.ip || req.connection?.remoteAddress || req.socket?.remoteAddress || 'unknown';
  }

  /**
   * @file rule-parser.js
   * @description .shield DSL Lexer & Recursive-Descent Parser.
   * 
   * ROLE IN ARCHITECTURE:
   * Compiles human-readable .shield rule files into an Abstract Syntax Tree (AST)
   * for high-performance execution by the rule-matcher.
   */
  reloadRules() {
    this.logger.info('Hot-reloading rules...');
    this.rules = [];
    this._loadRules();

    // Also notify modules that might be caching rule data (like smart-anomaly)
    for (const mod of this.modules) {
      if (typeof mod.module?.reload === 'function') {
        try { mod.module.reload(); } catch (e) { }
      }
    }
  }

  /**
   * Initializes YARA-like rule payloads from the filesystem and inline configs.
   */
  _loadRules() {
    try {
      this.rules.push(...loadRulesFromDir(this.options.rulesDir));
    } catch (err) {
      this.logger.warn(`Could not load default rules: ${err.message}`);
    }

    for (const filePath of this.options.customRulesFiles) {
      try {
        const { parseRuleFile } = require('./rule-parser');
        this.rules.push(...parseRuleFile(filePath));
      } catch (err) {
        this.logger.error(`Error loading rules from ${filePath}: ${err.message}`);
      }
    }

    if (this.options.customRules) {
      try { this.rules.push(...parseRules(this.options.customRules)); }
      catch (err) { this.logger.error(`Error loading inline custom rules: ${err.message}`); }
    }

    // Aho-Corasick Compilation for Fast-Path routing
    try {
      const { compileRules } = require('./rule-matcher');
      this.compiledRuleContext = compileRules(this.rules);
      this.logger.info(`Engine compiled ${this.rules.length} rules into Aho-Corasick context.`);
    } catch (err) {
      this.logger.error(`Aho-Corasick rule compilation failed: ${err.message}`);
    }
  }

  /**
   * Dynamically loads heuristic detection modules into the analysis pipeline.
   */
  _loadModules() {
    const map = {
      anomaly: '../modules/anomaly',
      smartAnomaly: '../modules/smart-anomaly',
      honeypot: '../modules/honeypot',
      pathTraversal: '../modules/path-traversal',
      commandInjection: '../modules/command-injection',
      botDetection: '../modules/bot-detection',
      sessionAnomaly: '../modules/session-anomaly',
      apiAbuse: '../modules/api-abuse',
      ddosProtection: '../modules/ddos-protection',
      fingerprinter: '../modules/fingerprinter',
      reputation: '../modules/reputation',
      adaptiveBaselines: '../modules/adaptive-baselines',
    };

    for (const [name, modulePath] of Object.entries(map)) {
      if (!this.options.modules[name]) continue;
      try {
        const mod = require(modulePath);
        this.modules.push({ name, check: mod.check, module: mod });
      } catch (err) {
        // Suppressing deeply nested crashes to prevent halting the entire boot process.
        this.logger.warn(`Module "${name}" not loaded: ${err.message}`);
      }
    }
  }

  /**
   * Central evaluation loop: Processes the request against all security layers.
   * @param {Object} req - The raw HTTP request object.
   * @param {Object} [options] - Analysis options (e.g. { trace: true }).
   * @returns {Promise<Object>} The verdict map including { blocked, matches, riskScore, trace }.
   */
  async analyze(req, res, opts = {}) {
    const startOverall = process.hrtime.bigint();
    const reqStartMs = Date.now();
    this.stats.totalRequests++;

    const trace = [];
    const addTrace = (step, data) => {
      const now = process.hrtime.bigint();
      const elapsed = Number(now - startOverall) / 1e6; // ms
      trace.push({ step, data, ms: elapsed.toFixed(3) });
    };

    addTrace('engine_entry', { method: req.method, url: req.url, ip: req.ip });

    req.clientIp = this._extractIP(req);
    addTrace('ip_resolved', { ip: req.clientIp });

    if (this._isExcluded(req)) {
      addTrace('engine_exit', { reason: 'whitelist_match' });
      return { blocked: false, matches: [], decodedReq: null, riskScore: 0, trace };
    }

    addTrace('decoding_start', { rawUrl: req.url, bodyType: typeof req.body });

    // Unification: Ensure body is a string (prevents Crash-on-JSON)
    let rawBodyStr = typeof req.body === 'object' ? JSON.stringify(req.body) : (req.body || "");

    // Padding/ReDoS protection: Collapse spaces and limit size
    if (rawBodyStr.length > 512 * 1024) {
      rawBodyStr = rawBodyStr.slice(0, 512 * 1024);
    }
    // Collapse excessive whitespace to prevent ReDoS on massive padding
    rawBodyStr = rawBodyStr.replace(/\s{10,}/g, ' ');

    req.body = rawBodyStr;

    const decodedReq = decodeRequest(req);

    if (res && typeof res.writeHead === 'function' && !res._reconHooked) {
      res._reconHooked = true;
      const originalWriteHead = res.writeHead;
      res.writeHead = function(statusCode) {
        if (statusCode === 404 || statusCode === 403) {
          recordReconAttempt(req.clientIp, decodedReq.path, statusCode);
        }
        originalWriteHead.apply(res, arguments);
      };
    }

    if (/(\/\.env|\/wp-admin|\/actuator)/i.test(decodedReq.path)) {
      recordReconAttempt(req.clientIp, decodedReq.path, 404);
    }

    // Ensure decoded body is a string for modules (Crash-on-JSON fix)
    if (typeof decodedReq.body === 'object' && decodedReq.body !== null) {
      decodedReq.body = JSON.stringify(decodedReq.body);
    }

    decodedReq.ip = req.clientIp;
    addTrace('decoding_complete', {
      path: decodedReq.path,
      queryKeys: Object.keys(decodedReq.query),
      bodyType: typeof decodedReq.body,
      jsonSmuggling: !!decodedReq.jsonSmuggling
    });

    const allMatches = [];
    let cumulativeRiskScore = 0;

    // 2. Protocol Anomaly Check
    const allowedMethods = ['GET', 'POST', 'PUT', 'DELETE', 'HEAD', 'OPTIONS', 'PATCH'];
    if (!allowedMethods.includes(decodedReq.method)) {
      allMatches.push({
        rule: 'protocol_anomaly:verb_tampering',
        severity: 'high',
        category: 'bypass',
        description: `Unusual HTTP method detected: ${decodedReq.method}`
      });
      cumulativeRiskScore += 30; // High severity score
    }

    if (decodedReq.jsonSmuggling) {
      allMatches.push({
        rule: 'protocol_anomaly:json_smuggling',
        severity: 'critical',
        category: 'zero-day',
        description: 'Duplicate keys detected in JSON body'
      });
      cumulativeRiskScore += 50; // Critical severity score
    }

    // Check for large headers (Buffer Overflow / DoS protection)
    const totalHeaderSize = Object.values(req.headers || {}).join('').length;
    if (totalHeaderSize > 16384) {
      allMatches.push({
        rule: 'protocol_anomaly:oversized_headers',
        severity: 'critical',
        category: 'dos',
        description: `Oversized headers detected (${totalHeaderSize} bytes)`
      });
      cumulativeRiskScore += 50;
    }

    for (const mod of this.modules) {
      const modStart = process.hrtime.bigint();
      try {
        const matches = await mod.check(decodedReq);
        const modEnd = process.hrtime.bigint();
        const modMs = Number(modEnd - modStart) / 1e6;

        addTrace('module_exec', {
          name: mod.name,
          matches: matches?.length || 0,
          durationMs: modMs.toFixed(3)
        });

        if (matches && matches.length > 0) {
          allMatches.push(...matches);
          for (const match of matches) {
            if (match.score) cumulativeRiskScore += match.score;
            else if (match.severity === 'critical') cumulativeRiskScore += 30;
            else if (match.severity === 'high') cumulativeRiskScore += 15;
            else if (match.severity === 'medium') cumulativeRiskScore += 7;
            else cumulativeRiskScore += 2;
          }
        }
      } catch (err) {
        addTrace('module_error', { name: mod.name, error: err.message });
        this.logger.error(`Module ${mod.name} failed:`, err);
      }
    }

    addTrace('rule_matching_start', { ruleCount: this.rules.length });
    const { matchCompiledRules } = require('./rule-matcher');
    const ruleMatches = this.compiledRuleContext
      ? matchCompiledRules(this.compiledRuleContext, decodedReq)
      : [];
    if (ruleMatches.length > 0) {
      addTrace('rule_matches', { count: ruleMatches.length, matches: ruleMatches });
      allMatches.push(...ruleMatches);
      for (const m of ruleMatches) {
        if (m.severity === 'critical') cumulativeRiskScore += 30;
        else if (m.severity === 'high') cumulativeRiskScore += 15;
        else if (m.severity === 'medium') cumulativeRiskScore += 7;
        else cumulativeRiskScore += 2;
      }
    }

    // Fast fail check: Save CPU if payload is fully clean
    if (!allMatches.length) {
      if (this.options.logging?.level === 'debug') {
        this.logger.info(`Clean request processed: ${decodedReq.method} ${decodedReq.rawUrl}`, { trace });
      }
      return { blocked: false, matches: [], decodedReq, riskScore: 0, trace };
    }

    /**
     * RISK AGGREGATION ENGINE (Deep Dive)
     * Maps extracted anomaly signals against Endpoint Complexity Constraints.
     */
    const sensitivity = this._getEndpointSensitivity(decodedReq.path || decodedReq.url || '');
    cumulativeRiskScore = 0; // Reset for sensitivity-weighted calculation

    for (const match of allMatches) {
      let baseCost = 0;
      if (typeof match.score === 'number' && match.score > 0) {
        baseCost = match.score;
      } else {
        baseCost = SEVERITY_WEIGHTS[match.severity] || 0;
      }
      cumulativeRiskScore += (baseCost * sensitivity);
    }

    // --- Cross-Module Signal Boosting ---
    const categoryHits = new Set(allMatches.map(m => m.category || (m.rule ? m.rule.split(':')[0] : 'unknown')));

    if (categoryHits.size >= 3) {
      cumulativeRiskScore *= 1.5;
    }
    if (categoryHits.size >= 4) {
      cumulativeRiskScore *= 2.0;
    }

    const isBot = allMatches.some(m => m.rule?.includes('fingerprinter') || m.rule?.includes('bot'));
    const hasPayloadAnomaly = allMatches.some(m => m.rule?.includes('anomaly') || m.rule?.includes('injection'));
    if (isBot && hasPayloadAnomaly) {
      cumulativeRiskScore *= 1.8;
    }
    // --- End Boosting ---

    // --- APT Kill Chain Correlation ---
    const ipTaint = getReputationTaint(decodedReq.ip);
    if (ipTaint > 15 && isSensitiveTarget(decodedReq.path)) {
      cumulativeRiskScore += ipTaint; // Full penalty application
      allMatches.push({
        rule: 'recon_to_exploit_correlation',
        severity: 'high',
        category: 'apt_sequence',
        description: `Zero-Day risk: Exploitation attempt on sensitive endpoint after reconnaissance (Taint: ${ipTaint})`
      });
    }

    let dynamicBlockThreshold = this.options.blockThreshold;

    /**
     * FALSE POSITIVE: CIRCUIT BREAKER
     * We dynamically discount the risk threshold if this user has established Trust.
     * Prevents IP drift and noisy double-click bans on validated users.
     */
    if (this.options.modules.reputation !== false) {
      try {
        const { getReputation } = require('../modules/reputation');
        const userRep = getReputation(decodedReq.ip);

        // If they have 0 incidents and their history spans more than 6 hours, give them leeway
        if (userRep.score === 0 && userRep.firstSeen) {
          const historyHours = (Date.now() - userRep.firstSeen) / (1000 * 60 * 60);
          if (historyHours > 6) {
            dynamicBlockThreshold = Math.floor(dynamicBlockThreshold * 1.5); // 50% leniency bonus (Circuit Breaker)
          }
        }
      } catch (e) {
        // Suppress reputation link errors
      }
    }

    const blockedByScore = this.options.mode === 'block' && cumulativeRiskScore >= dynamicBlockThreshold;
    const highestSeverity = this._getHighestSeverity(allMatches);

    if (res && typeof res.on === 'function') {
      res.on('finish', () => {
        const duration = Date.now() - reqStartMs;
        const statusCode = res.statusCode || 200;

        // 1. Blind Injection
        if (duration > 3000 && cumulativeRiskScore > 5 && cumulativeRiskScore < dynamicBlockThreshold) {
          try {
            require('../modules/reputation').record(decodedReq.ip, 'blind_sqli', 'high');
            this.logger.warn(`Blind injection suspected: Backend delay ${duration}ms on low-score request from ${decodedReq.ip}`);
          } catch (e) { }
        }

        // 2. Error Spike (Crash Analysis)
        if (statusCode >= 500) {
          if (!this.errorCache) this.errorCache = new Map();
          const errorKey = `errors:${decodedReq.ip}`;
          const errorCount = (this.errorCache.get(errorKey) || 0) + 1;
          this.errorCache.set(errorKey, errorCount);

          if (errorCount > 5) {
            this.logger.warn(`Error spike anomaly: IP ${decodedReq.ip} generated ${errorCount} 500 errors. Possible DoS or Fuzzing.`);
            try { require('../modules/reputation').record(decodedReq.ip, 'error_spike', 'high'); } catch (e) { }
          }
          if (this.errorCache.size > 5000) this.errorCache.delete(this.errorCache.keys().next().value);
        }

        // 3. Exfiltration Detection
        const contentLength = parseInt(res.getHeader ? res.getHeader('content-length') : 0, 10) || 0;
        if (contentLength > 0 && typeof require === 'function') {
          try {
            const bl = require('../modules/adaptive-baselines').getBaseline(decodedReq.path || '/');
            if (bl) {
              bl.avgResponseSize = bl.avgResponseSize ? bl.avgResponseSize * 0.9 + contentLength * 0.1 : contentLength;
              if (contentLength > bl.avgResponseSize * 10 && contentLength > 100000) {
                this.logger.warn(`Exfiltration suspected: Response size ${contentLength} exceeds baseline ${Math.round(bl.avgResponseSize)} for ${decodedReq.path}`);
                require('../modules/reputation').record(decodedReq.ip, 'data_exfiltration', 'high');
              }
            }
          } catch (e) { }
        }
      });
    }

    const traceId = crypto.randomUUID();
    const startTime = Date.now();

    const event = {
      traceId,
      riskScore: cumulativeRiskScore,
      highestSeverity,
      matches: allMatches,
      request: {
        ip: decodedReq.ip,
        method: decodedReq.method,
        url: decodedReq.rawUrl,
        userAgent: decodedReq.userAgent,
      }
    };

    // Active Mitigation Check
    const mitigationAction = this.mitigation.process(req, res, event);
    const blocked = blockedByScore || mitigationAction?.type === 'block';

    const finalEvent = {
      timestamp: new Date().toISOString(),
      blocked,
      riskScore: cumulativeRiskScore,
      highestSeverity: highestSeverity,
      request: {
        ip: decodedReq.ip,
        method: decodedReq.method,
        url: decodedReq.rawUrl,
        userAgent: req.headers['user-agent'] || 'none'
      },
      matches: allMatches,
      trace
    };

    // LOG EVERY SNEEZE (Always call attack() for full trace logging)
    this.logger.attack(finalEvent);

    if (this.options.modules.reputation !== false && blocked) {
      try {
        const { record } = require('../modules/reputation');
        record(decodedReq.ip, allMatches[0]?.category || 'unknown', highestSeverity);
      } catch { }
    }

    if (this.options.autoRules !== false && blocked) {
      for (const match of allMatches) {
        this._generateAutoRule(match, decodedReq);
      }
    }

    this.stats.detectedThreats += allMatches.length;
    if (blocked) this.stats.blockedRequests++;

    if (allMatches.length > 0) {
      this.emit('threat', { ...event, blocked, mitigation: mitigationAction });
    }

    // Handle Throttling (Blocking delay)
    if (mitigationAction?.type === 'throttle' && !blocked) {
      await new Promise(resolve => setTimeout(resolve, mitigationAction.delay));
    }

    return {
      blocked,
      riskScore: cumulativeRiskScore,
      highestSeverity: highestSeverity,
      matches: allMatches,
      decodedReq,
      mitigation: mitigationAction,
      trace
    };
  }

  /**
   * DLP (Data Loss Prevention) Scanner
   * Analyzes response bodies for sensitive data leakage.
   */
  analyzeResponse(body) {
    const patterns = [
      { name: 'dlp:system-files', regex: /root:x:0:0|\[boot loader\]/i, severity: 'critical' },
      { name: 'dlp:credentials', regex: /password\s*[:=]\s*[^\s,]{4,}/i, severity: 'high' },
      { name: 'dlp:credit-card', regex: /\b(?:\d[ -]*?){13,16}\b/, severity: 'medium' },
      { name: 'dlp:private-key', regex: /-----BEGIN (RSA|EC|OPENSSH) PRIVATE KEY-----/, severity: 'critical' }
    ];

    const matches = [];
    if (typeof body !== 'string') return matches;

    for (const p of patterns) {
      if (p.regex.test(body)) {
        matches.push({ rule: p.name, severity: p.severity, description: 'Sensitive data detected in response' });
      }
    }
    return matches;
  }

  /**
   * Formats the attack evidence structure mapping for Kibana/Datadog dashboards.
   * @param {Object} match - The hit result from a detector.
   * @returns {string} Stringified payload excerpt.
   */
  _formatEvidence(match) {
    if (match.analysis?.factors) {
      return match.analysis.factors.map(f => `[${f.name}] ${f.detail}`).join(' | ');
    }
    if (match.matchedPatterns?.length) {
      return match.matchedPatterns.map(p => `${p.name}: "${p.matched}"`).join(', ');
    }
    return '';
  }

  /**
   * Pre-filter whitelist validation. Checks if the URL path or Client IP explicitly bypasses WAF.
   * @param {Object} req - The inbound request.
   * @returns {boolean} True if excluded.
   */
  _isExcluded(req) {
    const p = req.path || req.url?.split('?')[0] || '';
    const ip = req.clientIp || this._extractIP(req);

    for (const ex of this.options.excludePaths) {
      if (typeof ex === 'string' && p.startsWith(ex)) return true;
      if (ex instanceof RegExp && ex.test(p)) return true;
    }
    return this.options.excludeIPs.includes(ip);
  }

  /**
   * Reduces the matches array down to its maximum perceived threat tier.
   * @param {Array} matches - The compiled list of threat signatures.
   * @returns {string} Semantic severity ('info', 'critical', etc).
   */
  _getHighestSeverity(matches) {
    let h = 'info', hp = 0;
    for (const m of matches) {
      const p = SEVERITY_PRIORITY[m.severity] || 0;
      if (p > hp) { hp = p; h = m.severity; }
    }
    return h;
  }

  /**
   * Correlates the path context with the Sensitivity Matrix to scale weights.
   * @param {string} path - URL path component.
   * @returns {number} Multiplier float (e.g. 2.5).
   */
  _getEndpointSensitivity(path) {
    for (const rule of ENDPOINT_SENSITIVITY) {
      if (rule.pattern.test(path)) return rule.multiplier;
    }
    return 1.0;
  }

  _formatGeo(geo) {
    if (!geo) return 'Unknown (Local/Internal)';
    const parts = [];
    if (geo.country) parts.push(geo.country);
    if (geo.city) parts.push(`(${geo.city})`);
    if (geo.asn) parts.push(`AS${geo.asn}`);
    if (geo.org) parts.push(geo.org);
    return parts.length ? parts.join(' ') : 'Unknown';
  }

  _detectDevice(ua) {
    if (!ua) return 'unknown';
    const l = ua.toLowerCase();
    if (/mobile|android|iphone|ipad|phone/i.test(l)) return 'mobile';
    if (/tablet|kindle|playbook/i.test(l)) return 'tablet';
    return 'desktop';
  }

  /**
   * Creates the final JSON block payload sent to attacking clients.
   * @param {Array} matches - Threat array.
   * @param {string} severity - Highest severity tier.
   * @returns {string} Stringified block message mapping.
   */
  getBlockResponse(matches, severity) {
    if (this.options.blockMessage) {
      return typeof this.options.blockMessage === 'function'
        ? this.options.blockMessage(matches) : this.options.blockMessage;
    }
    return JSON.stringify({
      error: 'Request Blocked',
      reason: 'ShieldWall detected a potential security threat',
      severity,
      rules: matches.map(m => m.rule),
      timestamp: new Date().toISOString(),
    });
  }

  /**
   * Retrieves runtime metrics for APM integration.
   * @returns {Object} Metric Map mapping.
   */
  getStats() {
    return {
      ...this.stats,
      uptime: Date.now() - this.stats.startTime,
      rulesLoaded: this.rules.length,
      modulesActive: this.modules.length,
      autoGeneratedRules: this._autoGeneratedHashes.size,
    };
  }

  /**
   * Generates localized .shield rules dynamically if an anomalous payload breaches 
   * strong heuristics. Prevents zero-day spread by mutating to regex blocks.
   * @param {Object} match - The threat trigger.
   * @param {Object} decodedReq - Normalised extraction container.
   */
  _generateAutoRule(match, decodedReq) {
    if (!this.options.autoGenerateRules) return;
    if (match.rule !== 'smart_anomaly_detection' || match.severity !== 'critical') return;

    if (!decodedReq?.rawBody || decodedReq.rawBody.length < 10) return;
    if (this._autoGeneratedHashes.size >= MAX_AUTO_RULES) return;
    if (!match.analysis?.novelIndicators || match.analysis.novelIndicators.length < 3) return;

    const bodyPrefix = decodedReq.rawBody.substring(0, 32);
    let escaped = bodyPrefix.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/\s+/g, '\\s+');
    if (escaped.length < 8) return;

    const hash = crypto.createHash('md5').update(escaped).digest('hex').substring(0, 8);
    if (this._autoGeneratedHashes.has(hash)) return;

    this._autoGeneratedHashes.add(hash);
    const ruleId = `auto_block_${hash}`;

    const ruleText = `\nrule ${ruleId} : autogenerated {
    meta:
        author = "shieldwall-autodetect"
        description = "Auto-generated from anomaly — review and promote or it expires"
        severity = "high"
        category = "0day_candidate"
        generated_at = "${new Date().toISOString()}"
        ttl_days = ${AUTO_RULE_TTL_DAYS}
    strings:
        $p1 = /${escaped}/i
    condition:
        $p1
}`;

    const rulesFile = path.join(this.options.rulesDir, 'autogenerated.shield');
    try {
      fs.appendFileSync(rulesFile, ruleText, 'utf8');
      this.logger.info(`Auto-generated new shield rule: ${ruleId}`);

      this.rules.push(...parseRules(ruleText));
    } catch (err) {
      this.logger.error(`Failed to auto-generate rule: ${err.message}`);
    }
  }

  /**
   * Safely shuts down the orchestrator processes.
   */
  destroy() {
    if (this.reporting) this.reporting.destroy();
    for (const mod of this.modules) {
      if (typeof mod.module?.destroy === 'function') {
        try { mod.module.destroy(); } catch (e) { }
      }
    }
    this.removeAllListeners();
  }
}

module.exports = ShieldWallEngine;
